apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQU0rNHVCVWZoQy9ka0hNR3RqaWtNTTR3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa05UUmlZV0psTlRVdE5EWmpaaTAwT0RRMExXSmhaVEV0WlRsak9EYzNPRFU1TlRBMwpNQ0FYRFRJMU1URXhOakU0TlRJeE9Gb1lEekl3TlRVeE1UQTVNVGsxTWpFNFdqQXZNUzB3S3dZRFZRUURFeVExCk5HSmhZbVUxTlMwME5tTm1MVFE0TkRRdFltRmxNUzFsT1dNNE56YzROVGsxTURjd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FEYUxqZlRrc2RnbjJOQW56am5SL3BQOXpVMEo4QTRwUkNNdnNMUQpxZitKU1d0WnVYSFRBQUJza1p3c2RJbzk5c3E2Q1pYb0V3eWk3bldnWnhTVGpGeDNwZ0twbG5RdldNN2RnRkNCCkUyMVp6TmRLSE5ZalFQYTJ5ZDNVejBVbHpnVTRuRmZIclBLRTBrRWtBMys1SlFIQ095K3JPSWk5RjRVK1VmcWMKa29laGtwcHc4VGdjNFRCQVZkUVRQcTk0MnN2cVhnMVFrSThmYzV6d2IzMVhtQ1BwQVlWUzRIbVlheERsWnoxVApsWUNwbC84QzU3Mng2ancvK09CWk4xaWFidkdneVVheDJ4endzbGMrcGZlckpjV2x6bEQ0alViOVE3VGdYdk5vClZCZWZLYkxwTUZYaEdOZHBwOFhIUnBlei9VdzZWTXJQNndxWEZrMnN1NnU3bTEwQzYvcXJzYXNkaGlTMFQyT2MKMTVZM0NQYlFRdWxxL3JCdnlIWjJWdXZocjd2Q1UvMXdYTHZRRG5KSEZBWEh3NWFiRzk5RHQ4TlFxR0FiTDNJLwovVDl6c3VWZDdYanprcHRlYXZwNmZvY2ZJc0pzS0Z5cFd4aE5idFhWRUpmcHBGSXg4dnRQZVQ0YUM5d2hqMTFXCldLZnNTSm1aR2hRKzlBVlVzMCtDSGZ6MWtvTUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQUZGWUwvN3huRk1yOUZhcFJDZ1p1WEZrbTlyTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRRERNY1hUMHBuZ2x3SFBnYUt0V2dUTzdzaWhZbXg2endLUWthWFRNazUwCjNDRWQ4N2JDMHd6ejJVOW5oZFBPN3VYYTRxRm52UDF2Wjl4N1BBNlFJV0RrL0Rvb2NEaC9lUm5BMUdlMWFXc0MKZE9TcjRqbUF1R0tva2RGWE8rU3NnMnp6Y0hIS3ErM3hPWlFvNUpSNE02RzFoYlY3anN1OWIxajllT3paZjdEeAo1bCtMK21MZGRKanpyV2dKZ29YOXNsNUdyYmxTbkhScC8rbzk2SGZnM0Q2NHcvQ0YrL1FTUHdDdk5lTmhrQjU4CnVZOXFrenkyMUlNVnIvdFU1NDZyQTgyd0ZqNm1wTDY5R0Rlano3Mjl1dFFmdmNYYVllL00wNkxuS0k1WTBZSXIKWWdMb1dHT2c5U1orNGMyV2tQckVTTWpDamdiNGpjRDdzVTNJd0tPUUcrY05GS3JmQ1BnZWEvbmtIU0c1U2xBQwpRMUhVdC9rTk5UakExKzhBN3NCTytXWlh2aktOU3lJL0M5aUlvZWJyV21GZzlVaGFocjl6Mk8wTzlyNnd6OEVIClk3MWpaVEdzZGY4aTk0S2twcis0Z2lsR3doZlpremFjUkZ3cWpacjdhZnNla1M2dkhaRUtiY3c4M05QaG9DQUsKeDR4U05XK3FIY1I3L0N4OC9KRkcwNnc9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://136.113.117.157
  name: gke_flowmaestro-prod_us-central1_flowmaestro-cluster
contexts:
- context:
    cluster: gke_flowmaestro-prod_us-central1_flowmaestro-cluster
    user: gke_flowmaestro-prod_us-central1_flowmaestro-cluster
  name: gke_flowmaestro-prod_us-central1_flowmaestro-cluster
current-context: gke_flowmaestro-prod_us-central1_flowmaestro-cluster
kind: Config
preferences: {}
users:
- name: gke_flowmaestro-prod_us-central1_flowmaestro-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      provideClusterInfo: true

